# Generated by Django 4.0.5 on 2022-06-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('takes_time', models.TimeField(verbose_name='Время выполнения (минут)')),
                ('exist', models.BooleanField(verbose_name='Действует')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('show_on_main_page', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
