# Generated by Django 4.0.5 on 2022-06-02 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Рабочий день')),
                ('start', models.TimeField(default=datetime.time(10, 0), verbose_name='Начало дня')),
                ('end', models.TimeField(default=datetime.time(22, 0), verbose_name='Конец дня')),
                ('is_reserved_hours', models.CharField(default='', max_length=255, verbose_name='Занятые часы')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Час')),
                ('booked', models.BooleanField(default=False, verbose_name='Зарезервирован')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.schedule', verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Рабочий час',
                'verbose_name_plural': 'Рабочие часы',
            },
        ),
    ]
