# Generated by Django 4.0.5 on 2022-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_schedule_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='appointment_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID записи'),
            preserve_default=False,
        ),
    ]
