# Generated by Django 4.0.5 on 2022-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_hours_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID записи'),
        ),
    ]
