# Generated by Django 4.0.5 on 2022-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_hours_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(unique=True, verbose_name='Рабочий день'),
        ),
    ]
