# Generated by Django 4.0.5 on 2022-06-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='hour',
            field=models.TimeField(unique_for_date=True, verbose_name='Час'),
        ),
    ]
