# Generated by Django 4.0.5 on 2022-06-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_hours_hour_alter_hours_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.schedule', verbose_name='Рабочий день'),
        ),
    ]
